### ISSUE TITLE
Implement the alternative schema

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#31]
Although measurements have been a bit mixed, I do want to try implementing the alternative schema from #27: no _meta columns, just a 'message' table.

**Comment by lmcmicu** [comment]
I just realised that there is a problem with the planned new schema. I think we need to add a `value` column to the `message` table, i.e.,
```
table | row | column | value | level | rule | message
```
Otherwise it will not be possible to round-trip, and it will also be impossible to have multiple validation failures per cell.

I will continue the implementation using this new added column. I don't expect this to be controversial, but I want to note it in case.

**Comment by jamesaoverton** [comment]
Yeah, I think that's the right solution. In the work I've been doing this week, it's also just nice to have the 'value' visible when looking at the message table.

If there are multiple messages for a cell then the value will be duplicated, which is a bit inefficient. If there are multiple values then there's a chance for them to differ. But I think we just deal with those problems.
