### ISSUE TITLE
Support column labels

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.rs#49]
I would like the 'column' table to have a 'label' column, which would provide a human-readable label for the column when the table is displayed (e.g. in the Nanobot web interface). If no label is provided for a given column, the default should be just the column name. I would also like this exposed in the VALVE config, so it's easy to use from Nanobot, for example. 

I suppose the 'label' column could be optional, but that seems like more work.

**Comment by lmcmicu** [comment]
@jamesaoverton wrote: "I suppose the 'label' column could be optional, but that seems like more work."

I'm not sure what you are referring to here, but from the point of view of VALVE there is no problem making this optional. It is  actually "more work" (i.e., see the single line change to src/lib.rs in [this commit](https://github.com/ontodev/valve.rs/pull/51/commits/2f39abd4989ad19c7ca2e1b18c4c7e300a62ff2d) to make it required than it is to make it optional, at least from valve's point of view.

Whether it is optional from nanobot's (or some other calling application's) point of view is another matter.

Let me know if you would like me to make it optional from valve's point of view. Otherwise this should be closed by PR #51
